### ISSUE TITLE
Does this plugin also pause/resume any media that is playing?

### ISSUE THREAD

**Issue by gvdhoven** [Supergiovane/node-red-contrib-sonospollytts#53] opened 2020-11-14 09:41 UTC
Question: Does this plugin also pause/resume any media that is playing?

**Comment by Supergiovane** [comment] 2020-11-14 11:29
Hi
It stops the play, but it doesn’t resume after speech. You need to use another sonos node and link the output of sonospollytts to a function that resumes the current queue.

**Comment by gvdhoven** [comment] 2020-11-16 10:01
ah great, so it _is_ capable of interrupting a playing stream with the announcement, i just have to use another node to restart the playing?

**Comment by Supergiovane** [comment] 2020-11-16 10:23
Yes, exactly.
Please beer in mind, that all Sonos API that we developers use, are unofficial and undocumented so we must stitch with the bare minimum ones.

**Comment by Supergiovane** [comment] 2020-11-25 08:22
Duplicate of #54

**Closed by Supergiovane** 2020-11-25 08:22 UTC
